TASK-55175: Implement copy and move processes attachments nodes
exoplatform/processes pull request #47
Opened 2022-03-16 15:33 UTC by hakermi

Implement copy and move processes attachments nodes

2022-03-17 09:49 UTC, mkrout requested changes

2022-03-17 09:49 UTC, mkrout commented on processes-services/src/main/java/org/exoplatform/processes/service/ProcessesAttachmentServiceImpl.java
> +    permissions.put("*:/platform/processes", PermissionType.ALL);
Should not set hardcoded permissions, we may have cases  that process are created in other space projects or maybe personal projects

2022-03-17 09:52 UTC, hakermi commented on processes-services/src/main/java/org/exoplatform/processes/service/ProcessesAttachmentServiceImpl.java
> +    permissions.put("*:/platform/processes", PermissionType.ALL);
I set the permissions for the processes group and admins group and **not for the space processes,** the processes admins should have access to the attachments where ever they were stored isn't it ?

2022-03-18 15:36 UTC, mkrout approved these changes

2022-03-18 15:38 UTC, merged